// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.0
// source: record.proto

package record

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveStatus_LiveStatusEnum int32

const (
	LiveStatus_NONE      LiveStatus_LiveStatusEnum = 0
	LiveStatus_LIVE      LiveStatus_LiveStatusEnum = 1
	LiveStatus_PREPARING LiveStatus_LiveStatusEnum = 2
)

// Enum value maps for LiveStatus_LiveStatusEnum.
var (
	LiveStatus_LiveStatusEnum_name = map[int32]string{
		0: "NONE",
		1: "LIVE",
		2: "PREPARING",
	}
	LiveStatus_LiveStatusEnum_value = map[string]int32{
		"NONE":      0,
		"LIVE":      1,
		"PREPARING": 2,
	}
)

func (x LiveStatus_LiveStatusEnum) Enum() *LiveStatus_LiveStatusEnum {
	p := new(LiveStatus_LiveStatusEnum)
	*p = x
	return p
}

func (x LiveStatus_LiveStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveStatus_LiveStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_record_proto_enumTypes[0].Descriptor()
}

func (LiveStatus_LiveStatusEnum) Type() protoreflect.EnumType {
	return &file_record_proto_enumTypes[0]
}

func (x LiveStatus_LiveStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveStatus_LiveStatusEnum.Descriptor instead.
func (LiveStatus_LiveStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3, 0}
}

type RecordMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*RecordMsg_Danmu
	//	*RecordMsg_LiveStatus
	//	*RecordMsg_Gift
	Content isRecordMsg_Content `protobuf_oneof:"content"`
}

func (x *RecordMsg) Reset() {
	*x = RecordMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMsg) ProtoMessage() {}

func (x *RecordMsg) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMsg.ProtoReflect.Descriptor instead.
func (*RecordMsg) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (m *RecordMsg) GetContent() isRecordMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *RecordMsg) GetDanmu() *DanmuRecord {
	if x, ok := x.GetContent().(*RecordMsg_Danmu); ok {
		return x.Danmu
	}
	return nil
}

func (x *RecordMsg) GetLiveStatus() *LiveStatus {
	if x, ok := x.GetContent().(*RecordMsg_LiveStatus); ok {
		return x.LiveStatus
	}
	return nil
}

func (x *RecordMsg) GetGift() *GiftRecord {
	if x, ok := x.GetContent().(*RecordMsg_Gift); ok {
		return x.Gift
	}
	return nil
}

type isRecordMsg_Content interface {
	isRecordMsg_Content()
}

type RecordMsg_Danmu struct {
	Danmu *DanmuRecord `protobuf:"bytes,1,opt,name=danmu,proto3,oneof"`
}

type RecordMsg_LiveStatus struct {
	LiveStatus *LiveStatus `protobuf:"bytes,2,opt,name=liveStatus,proto3,oneof"`
}

type RecordMsg_Gift struct {
	Gift *GiftRecord `protobuf:"bytes,3,opt,name=gift,proto3,oneof"`
}

func (*RecordMsg_Danmu) isRecordMsg_Content() {}

func (*RecordMsg_LiveStatus) isRecordMsg_Content() {}

func (*RecordMsg_Gift) isRecordMsg_Content() {}

type DanmuRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int32       `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Danmu      *DanmuInfo  `protobuf:"bytes,2,opt,name=danmu,proto3" json:"danmu,omitempty"`
	UnknownCmd *UnknownCmd `protobuf:"bytes,3,opt,name=unknownCmd,proto3" json:"unknownCmd,omitempty"`
}

func (x *DanmuRecord) Reset() {
	*x = DanmuRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DanmuRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuRecord) ProtoMessage() {}

func (x *DanmuRecord) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuRecord.ProtoReflect.Descriptor instead.
func (*DanmuRecord) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *DanmuRecord) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *DanmuRecord) GetDanmu() *DanmuInfo {
	if x != nil {
		return x.Danmu
	}
	return nil
}

func (x *DanmuRecord) GetUnknownCmd() *UnknownCmd {
	if x != nil {
		return x.UnknownCmd
	}
	return nil
}

type GiftRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int32       `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Gift       *Gift       `protobuf:"bytes,2,opt,name=gift,proto3" json:"gift,omitempty"`
	UnknownCmd *UnknownCmd `protobuf:"bytes,3,opt,name=unknownCmd,proto3" json:"unknownCmd,omitempty"`
}

func (x *GiftRecord) Reset() {
	*x = GiftRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftRecord) ProtoMessage() {}

func (x *GiftRecord) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftRecord.ProtoReflect.Descriptor instead.
func (*GiftRecord) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{2}
}

func (x *GiftRecord) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GiftRecord) GetGift() *Gift {
	if x != nil {
		return x.Gift
	}
	return nil
}

func (x *GiftRecord) GetUnknownCmd() *UnknownCmd {
	if x != nil {
		return x.UnknownCmd
	}
	return nil
}

type LiveStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32                     `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Status LiveStatus_LiveStatusEnum `protobuf:"varint,2,opt,name=status,proto3,enum=cn.tursom.record.LiveStatus_LiveStatusEnum" json:"status,omitempty"`
}

func (x *LiveStatus) Reset() {
	*x = LiveStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStatus) ProtoMessage() {}

func (x *LiveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStatus.ProtoReflect.Descriptor instead.
func (*LiveStatus) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3}
}

func (x *LiveStatus) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LiveStatus) GetStatus() LiveStatus_LiveStatusEnum {
	if x != nil {
		return x.Status
	}
	return LiveStatus_NONE
}

type UnknownCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd        string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	OriginData string `protobuf:"bytes,2,opt,name=originData,proto3" json:"originData,omitempty"`
}

func (x *UnknownCmd) Reset() {
	*x = UnknownCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnknownCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownCmd) ProtoMessage() {}

func (x *UnknownCmd) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownCmd.ProtoReflect.Descriptor instead.
func (*UnknownCmd) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{4}
}

func (x *UnknownCmd) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *UnknownCmd) GetOriginData() string {
	if x != nil {
		return x.OriginData
	}
	return ""
}

var File_record_proto protoreflect.FileDescriptor

var file_record_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x1a, 0x0b, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x35, 0x0a, 0x05, 0x64,
	0x61, 0x6e, 0x6d, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6e, 0x2e,
	0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x61,
	0x6e, 0x6d, 0x75, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x05, 0x64, 0x61, 0x6e,
	0x6d, 0x75, 0x12, 0x3e, 0x0a, 0x0a, 0x6c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73,
	0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x67, 0x69, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00,
	0x52, 0x04, 0x67, 0x69, 0x66, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x95, 0x01, 0x0a, 0x0b, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x64, 0x61, 0x6e,
	0x6d, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75,
	0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x12, 0x3c, 0x0a, 0x0a, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x0a, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x47, 0x69,
	0x66, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x04, 0x67, 0x69, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x75,
	0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x04, 0x67, 0x69, 0x66, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x0a, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x0a, 0x4c, 0x69,
	0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x43, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2b, 0x2e, 0x63, 0x6e, 0x2e, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x4c,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x33, 0x0a, 0x0e, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x50,
	0x52, 0x45, 0x50, 0x41, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x22, 0x3e, 0x0a, 0x0a, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x12, 0x42, 0x06, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x48, 0x01, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData = file_record_proto_rawDesc
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_proto_rawDescData)
	})
	return file_record_proto_rawDescData
}

var file_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_record_proto_goTypes = []interface{}{
	(LiveStatus_LiveStatusEnum)(0), // 0: cn.tursom.record.LiveStatus.LiveStatusEnum
	(*RecordMsg)(nil),              // 1: cn.tursom.record.RecordMsg
	(*DanmuRecord)(nil),            // 2: cn.tursom.record.DanmuRecord
	(*GiftRecord)(nil),             // 3: cn.tursom.record.GiftRecord
	(*LiveStatus)(nil),             // 4: cn.tursom.record.LiveStatus
	(*UnknownCmd)(nil),             // 5: cn.tursom.record.UnknownCmd
	(*DanmuInfo)(nil),              // 6: cn.tursom.danmu.DanmuInfo
	(*Gift)(nil),                   // 7: cn.tursom.danmu.Gift
}
var file_record_proto_depIdxs = []int32{
	2, // 0: cn.tursom.record.RecordMsg.danmu:type_name -> cn.tursom.record.DanmuRecord
	4, // 1: cn.tursom.record.RecordMsg.liveStatus:type_name -> cn.tursom.record.LiveStatus
	3, // 2: cn.tursom.record.RecordMsg.gift:type_name -> cn.tursom.record.GiftRecord
	6, // 3: cn.tursom.record.DanmuRecord.danmu:type_name -> cn.tursom.danmu.DanmuInfo
	5, // 4: cn.tursom.record.DanmuRecord.unknownCmd:type_name -> cn.tursom.record.UnknownCmd
	7, // 5: cn.tursom.record.GiftRecord.gift:type_name -> cn.tursom.danmu.Gift
	5, // 6: cn.tursom.record.GiftRecord.unknownCmd:type_name -> cn.tursom.record.UnknownCmd
	0, // 7: cn.tursom.record.LiveStatus.status:type_name -> cn.tursom.record.LiveStatus.LiveStatusEnum
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	file_danmu_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DanmuRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnknownCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_record_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RecordMsg_Danmu)(nil),
		(*RecordMsg_LiveStatus)(nil),
		(*RecordMsg_Gift)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		EnumInfos:         file_record_proto_enumTypes,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_rawDesc = nil
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
